[project]
title = "ICC World Cup 2023 Batting Insights"
version = "0.1.0"
port = 8507
slug = "my-project-604197"
entrypoint = "hello.py"

[branding]
name = "Preswald Project"
logo = "images/logo.png" 
favicon = "images/favicon.ico"  
primaryColor = "#F89613"

[data.icc_wc_23_bat] 
type = "csv"
path = "data/icc_wc_23_bat.csv" 

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"